//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practicacinco.cero
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventos
    {
        public int eventoId { get; set; }
        public string descripcion { get; set; }
        public string fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
    }
}
